# PROJECT - Classification of diabetes risk

### Step 3 — Mapping Categorical Variables to Meaningful Labels

In this step, raw coded variables (e.g., `_SEX`) are inspected and converted into human-readable labels.

**Process followed:**
- Display unique values to verify coding structure
- then making those values as textual data for eg. 1- Male, 2- Female.
- Creating the COLUME to COLUMN_LABEL, improves clarity during EDA and helps interpret COLUMN status in plots and tables.

In [377]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plr
import seaborn as sns

### Loading the Cleaned & Imputed BRFSS 2024 Dataset

The dataset used in this step is the fully **cleaned** and **imputed** version of the BRFSS 2024 data.  
It is imported using the path below:

In [378]:
data = pd.read_csv(r"C:\Users\Junaid\MSC-DS\RM\STEP_1_BRFSS\CLEANED_IMPUTED_BRFSS24.csv")

In [379]:
data.shape

(449360, 29)

In [380]:
print(data.head())

   GENHLTH  _SEX  PHYSHLTH  MENTHLTH  POORHLTH  PERSDOC3  MEDCOST1  EXERANY2  \
0      3.0   2.0       2.0       7.0       7.0       2.0       2.0       1.0   
1      1.0   1.0       6.0       7.0       7.0       1.0       2.0       1.0   
2      2.0   1.0      30.0       7.0       1.0       3.0       1.0       1.0   
3      1.0   1.0       6.0       7.0       7.0       1.0       2.0       1.0   
4      3.0   1.0       6.0       7.0       7.0       1.0       2.0       2.0   

   CVDSTRK3  CHCKDNY2  ...  _TOTINDA  _IMPRACE  _RFDRHV9  _HLTHPL2  _RACE  \
0       2.0       2.0  ...       1.0       1.0       1.0       1.0    1.0   
1       2.0       2.0  ...       1.0       1.0       1.0       1.0    1.0   
2       2.0       2.0  ...       1.0       1.0       1.0       1.0    1.0   
3       2.0       2.0  ...       1.0       1.0       1.0       1.0    1.0   
4       2.0       2.0  ...       2.0       1.0       1.0       1.0    1.0   

   _AGEG5YR   _BMI5  ADDEPEV3  EMTSUPRT  DIABETE4  
0   

In [381]:
df = data.copy()

In [382]:
df.head()

GENHLTH  _SEX  PHYSHLTH  MENTHLTH  POORHLTH  PERSDOC3  MEDCOST1  EXERANY2  \
0      3.0   2.0       2.0       7.0       7.0       2.0       2.0       1.0   
1      1.0   1.0       6.0       7.0       7.0       1.0       2.0       1.0   
2      2.0   1.0      30.0       7.0       1.0       3.0       1.0       1.0   
3      1.0   1.0       6.0       7.0       7.0       1.0       2.0       1.0   
4      3.0   1.0       6.0       7.0       7.0       1.0       2.0       2.0   

   CVDSTRK3  CHCKDNY2  ...  _TOTINDA  _IMPRACE  _RFDRHV9  _HLTHPL2  _RACE  \
0       2.0       2.0  ...       1.0       1.0       1.0       1.0    1.0   
1       2.0       2.0  ...       1.0       1.0       1.0       1.0    1.0   
2       2.0       2.0  ...       1.0       1.0       1.0       1.0    1.0   
3       2.0       2.0  ...       1.0       1.0       1.0       1.0    1.0   
4       2.0       2.0  ...       2.0       1.0       1.0       1.0    1.0   

   _AGEG5YR   _BMI5  ADDEPEV3  EMTSUPRT  DIABETE4  
0      12.0  2249.0       2.0       1.0       3.0  
1      13.0  2583.0       2.0       1.0       3.0  
2       8.0  2253.0       2.0       2.0       3.0  
3      13.0  2509.0       2.0       1.0       3.0  
4       6.0  1977.0       2.0       4.0       3.0  

[5 rows x 29 columns]

In [383]:
df.isnull().sum()

GENHLTH     0
_SEX        0
PHYSHLTH    0
MENTHLTH    0
POORHLTH    0
PERSDOC3    0
MEDCOST1    0
EXERANY2    0
CVDSTRK3    0
CHCKDNY2    0
MARITAL     0
EDUCA       0
EMPLOY1     0
_INCOMG1    0
DIFFWALK    0
SMOKE100    0
LSATISFY    0
_METSTAT    0
SSBFRUT3    0
_TOTINDA    0
_IMPRACE    0
_RFDRHV9    0
_HLTHPL2    0
_RACE       0
_AGEG5YR    0
_BMI5       0
ADDEPEV3    0
EMTSUPRT    0
DIABETE4    0
dtype: int64

In [384]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 449360 entries, 0 to 449359
Data columns (total 29 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   GENHLTH   449360 non-null  float64
 1   _SEX      449360 non-null  float64
 2   PHYSHLTH  449360 non-null  float64
 3   MENTHLTH  449360 non-null  float64
 4   POORHLTH  449360 non-null  float64
 5   PERSDOC3  449360 non-null  float64
 6   MEDCOST1  449360 non-null  float64
 7   EXERANY2  449360 non-null  float64
 8   CVDSTRK3  449360 non-null  float64
 9   CHCKDNY2  449360 non-null  float64
 10  MARITAL   449360 non-null  float64
 11  EDUCA     449360 non-null  float64
 12  EMPLOY1   449360 non-null  float64
 13  _INCOMG1  449360 non-null  float64
 14  DIFFWALK  449360 non-null  float64
 15  SMOKE100  449360 non-null  float64
 16  LSATISFY  449360 non-null  float64
 17  _METSTAT  449360 non-null  float64
 18  SSBFRUT3  449360 non-null  float64
 19  _TOTINDA  449360 non-null  float64
 20  _IMP

In [385]:
df.describe()

GENHLTH           _SEX       PHYSHLTH       MENTHLTH  \
count  449360.000000  449360.000000  449360.000000  449360.000000   
mean        2.647804       1.524450       8.159182       8.595803   
std         1.047754       0.499402       7.362474       6.628956   
min         1.000000       1.000000       1.000000       1.000000   
25%         2.000000       1.000000       6.000000       7.000000   
50%         3.000000       2.000000       6.000000       7.000000   
75%         3.000000       2.000000       6.000000       7.000000   
max         5.000000       2.000000      30.000000      30.000000   

            POORHLTH       PERSDOC3       MEDCOST1       EXERANY2  \
count  449360.000000  449360.000000  449360.000000  449360.000000   
mean        8.203071       1.582862       1.904965       1.232829   
std         5.756078       0.699085       0.293264       0.422635   
min         1.000000       1.000000       1.000000       1.000000   
25%         7.000000       1.000000       2.000000       1.000000   
50%         7.000000       1.000000       2.000000       1.000000   
75%         7.000000       2.000000       2.000000       1.000000   
max        30.000000       3.000000       2.000000       2.000000   

            CVDSTRK3       CHCKDNY2  ...       _TOTINDA       _IMPRACE  \
count  449360.000000  449360.000000  ...  449360.000000  449360.000000   
mean        1.954662       1.947848  ...       1.232829       1.791310   
std         0.208044       0.222334  ...       0.422635       1.528474   
min         1.000000       1.000000  ...       1.000000       1.000000   
25%         2.000000       2.000000  ...       1.000000       1.000000   
50%         2.000000       2.000000  ...       1.000000       1.000000   
75%         2.000000       2.000000  ...       1.000000       2.000000   
max         2.000000       2.000000  ...       2.000000       6.000000   

            _RFDRHV9       _HLTHPL2          _RACE       _AGEG5YR  \
count  449360.000000  449360.000000  449360.000000  449360.000000   
mean        1.053294       1.055788       2.135108       7.666853   
std         0.224619       0.229513       2.335341       3.675574   
min         1.000000       1.000000       1.000000       1.000000   
25%         1.000000       1.000000       1.000000       5.000000   
50%         1.000000       1.000000       1.000000       8.000000   
75%         1.000000       1.000000       2.000000      11.000000   
max         2.000000       2.000000       8.000000      13.000000   

               _BMI5       ADDEPEV3       EMTSUPRT       DIABETE4  
count  449360.000000  449360.000000  449360.000000  449360.000000  
mean     2847.259812       1.788208       1.381029       2.728952  
std       630.483530       0.408579       0.829998       0.732036  
min      1200.000000       1.000000       1.000000       1.000000  
25%      2441.000000       2.000000       1.000000       3.000000  
50%      2744.000000       2.000000       1.000000       3.000000  
75%      3125.000000       2.000000       1.000000       3.000000  
max      9984.000000       2.000000       5.000000       4.000000  

[8 rows x 29 columns]

In [386]:
df.columns

Index(['GENHLTH', '_SEX', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PERSDOC3',
       'MEDCOST1', 'EXERANY2', 'CVDSTRK3', 'CHCKDNY2', 'MARITAL', 'EDUCA',
       'EMPLOY1', '_INCOMG1', 'DIFFWALK', 'SMOKE100', 'LSATISFY', '_METSTAT',
       'SSBFRUT3', '_TOTINDA', '_IMPRACE', '_RFDRHV9', '_HLTHPL2', '_RACE',
       '_AGEG5YR', '_BMI5', 'ADDEPEV3', 'EMTSUPRT', 'DIABETE4'],
      dtype='object')

### Mapping Variable: `GENHLTH` — General Health Status

For the variable **`GENHLTH`**, the numeric codes represent different self-reported health levels.  
To make these values easier to interpret during EDA and reporting, a new column  
**`GENHLTH_LABEL`** is created using .map().
For example, if the original value was 3.0, the mapped label becomes "Good".

You have to follow this same structure for all the columns by making new column named COLUMN_LABEL.

In [387]:
print(df['GENHLTH'].unique())
print(df['GENHLTH'].value_counts(dropna=False))

[3. 1. 2. 4. 5.]
GENHLTH
3.0    154527
2.0    143222
4.0     66875
1.0     62847
5.0     21889
Name: count, dtype: int64


In [388]:
df['GENHLTH_LABEL'] = df['GENHLTH'].map({
    1: 'Excellent',
    2: 'Very good',
    3: 'Good',
    4: 'Fair',
    5: 'Poor'
})


In [389]:
df[['GENHLTH', 'GENHLTH_LABEL']].head()

GENHLTH GENHLTH_LABEL
0      3.0          Good
1      1.0     Excellent
2      2.0     Very good
3      1.0     Excellent
4      3.0          Good

In [390]:
df.columns

Index(['GENHLTH', '_SEX', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PERSDOC3',
       'MEDCOST1', 'EXERANY2', 'CVDSTRK3', 'CHCKDNY2', 'MARITAL', 'EDUCA',
       'EMPLOY1', '_INCOMG1', 'DIFFWALK', 'SMOKE100', 'LSATISFY', '_METSTAT',
       'SSBFRUT3', '_TOTINDA', '_IMPRACE', '_RFDRHV9', '_HLTHPL2', '_RACE',
       '_AGEG5YR', '_BMI5', 'ADDEPEV3', 'EMTSUPRT', 'DIABETE4',
       'GENHLTH_LABEL'],
      dtype='object')

In [391]:
print(df['_SEX'].unique())
print(df['_SEX'].value_counts(dropna=False))
df['_SEX_LABEL'] = df['_SEX'].map({
    1: 'Male',
    2: 'Female'
})
df[['_SEX', '_SEX_LABEL']].head()


[2. 1.]
_SEX
2.0    235667
1.0    213693
Name: count, dtype: int64


_SEX _SEX_LABEL
0   2.0     Female
1   1.0       Male
2   1.0       Male
3   1.0       Male
4   1.0       Male

###### PHYSHLTH — Physical Health (Bad Days)

`PHYSHLTH` records how many days (0–30) a person felt physically unwell.  
We created a new label column by grouping the values into **bins**—which means slicing numeric ranges into categories.  
The bins used were: **0 days**, **1–5 days**, **6–15 days**, and **16–30 days**.  
This helps convert continuous day counts into clear, interpretable groups for EDA.
similerly we have to make bins for days columns into category, and rest mapped with their respected values 

In [392]:
print(df['PHYSHLTH'].unique())
print(df['PHYSHLTH'].describe())


[ 2.  6. 30.  7.  5. 14.  1. 25. 20.  3.  4. 15. 10.  8. 27. 12. 29. 28.
 21.  9. 19. 16. 23. 18. 17. 24. 11. 22. 13. 26.]
count    449360.000000
mean          8.159182
std           7.362474
min           1.000000
25%           6.000000
50%           6.000000
75%           6.000000
max          30.000000
Name: PHYSHLTH, dtype: float64


In [393]:
df['PHYSHLTH_LABEL'] = pd.cut(df['PHYSHLTH'], bins=[-1, 0, 5, 15, 30], 
                             labels=['0 days', '1-5 days', '6-15 days', '16-30 days'])


In [394]:
df[['PHYSHLTH', 'PHYSHLTH_LABEL']].head()


PHYSHLTH PHYSHLTH_LABEL
0       2.0       1-5 days
1       6.0      6-15 days
2      30.0     16-30 days
3       6.0      6-15 days
4       6.0      6-15 days

In [395]:
print(df['MENTHLTH'].unique())
print(df['MENTHLTH'].describe())


[ 7. 15.  1. 30.  2.  8. 10.  6.  5.  4.  9. 25.  3. 20. 29. 11. 12. 14.
 26. 17. 23. 21. 28. 18. 22. 13. 19. 16. 27. 24.]
count    449360.000000
mean          8.595803
std           6.628956
min           1.000000
25%           7.000000
50%           7.000000
75%           7.000000
max          30.000000
Name: MENTHLTH, dtype: float64


In [396]:
df['MENTHLTH_LABEL'] = pd.cut(df['MENTHLTH'], bins=[-1, 0, 5, 15, 30], 
                             labels=['0 days', '1-5 days', '6-15 days', '16-30 days'])


In [397]:
df[['MENTHLTH', 'MENTHLTH_LABEL']].head()


MENTHLTH MENTHLTH_LABEL
0       7.0      6-15 days
1       7.0      6-15 days
2       7.0      6-15 days
3       7.0      6-15 days
4       7.0      6-15 days

In [398]:
print(df['POORHLTH'].unique())
print(df['POORHLTH'].describe())


[ 7.  1. 14. 30. 20. 10. 25.  8.  2. 15.  4.  5.  3. 28. 18. 12.  6. 21.
  9. 27. 16. 24. 13. 19. 26. 23. 17. 11. 29. 22.]
count    449360.000000
mean          8.203071
std           5.756078
min           1.000000
25%           7.000000
50%           7.000000
75%           7.000000
max          30.000000
Name: POORHLTH, dtype: float64


In [399]:
df['POORHLTH_LABEL'] = pd.cut(df['POORHLTH'], bins=[-1, 0, 5, 15, 30], 
                             labels=['0 days', '1-5 days', '6-15 days', '16-30 days'])


In [400]:
df[['POORHLTH', 'POORHLTH_LABEL']].head()


POORHLTH POORHLTH_LABEL
0       7.0      6-15 days
1       7.0      6-15 days
2       1.0       1-5 days
3       7.0      6-15 days
4       7.0      6-15 days

In [401]:

print(df['PERSDOC3'].unique())
print(df['PERSDOC3'].value_counts(dropna=False))


[2. 1. 3.]
PERSDOC3
1.0    242623
2.0    151559
3.0     55178
Name: count, dtype: int64


In [402]:
df['PERSDOC3_LABEL'] = df['PERSDOC3'].map({
    1: 'Yes',
    2: 'No',
    3: 'Don’t know / Not sure'
})


In [403]:
df[['PERSDOC3', 'PERSDOC3_LABEL']].head()


PERSDOC3         PERSDOC3_LABEL
0       2.0                     No
1       1.0                    Yes
2       3.0  Don’t know / Not sure
3       1.0                    Yes
4       1.0                    Yes

In [404]:
print(df['MEDCOST1'].unique())
print(df['MEDCOST1'].value_counts(dropna=False))


[2. 1.]
MEDCOST1
2.0    406655
1.0     42705
Name: count, dtype: int64


In [405]:
df['MEDCOST1_LABEL'] = df['MEDCOST1'].map({
    1: 'CANT AFFORD',
    2: 'AFOORD'
})


In [406]:
df[['MEDCOST1', 'MEDCOST1_LABEL']].head()


MEDCOST1 MEDCOST1_LABEL
0       2.0         AFOORD
1       2.0         AFOORD
2       1.0    CANT AFFORD
3       2.0         AFOORD
4       2.0         AFOORD

In [407]:
print(df['EXERANY2'].unique())
print(df['EXERANY2'].value_counts(dropna=False))


[1. 2.]
EXERANY2
1.0    344736
2.0    104624
Name: count, dtype: int64


In [408]:
df['EXERANY2_LABEL'] = df['EXERANY2'].map({
    1:'Yes',
    2:'No'
}) 
# whether the respondent did any physical activity or exercise in the past 30 days.

In [409]:
df[['EXERANY2', 'EXERANY2_LABEL']].head()


EXERANY2 EXERANY2_LABEL
0       1.0            Yes
1       1.0            Yes
2       1.0            Yes
3       1.0            Yes
4       2.0             No

In [410]:
print(df['CVDSTRK3'].unique())
print(df['CVDSTRK3'].value_counts(dropna=False))

[2. 1.]
CVDSTRK3
2.0    428987
1.0     20373
Name: count, dtype: int64


In [411]:
df["CVDSTRK3_LABEL"] = df['CVDSTRK3'].map({
    1 :"Yes",
    2 : "No"
})

In [412]:
df[['CVDSTRK3', "CVDSTRK3_LABEL"]].head()

CVDSTRK3 CVDSTRK3_LABEL
0       2.0             No
1       2.0             No
2       2.0             No
3       2.0             No
4       2.0             No

In [413]:
df.columns

Index(['GENHLTH', '_SEX', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PERSDOC3',
       'MEDCOST1', 'EXERANY2', 'CVDSTRK3', 'CHCKDNY2', 'MARITAL', 'EDUCA',
       'EMPLOY1', '_INCOMG1', 'DIFFWALK', 'SMOKE100', 'LSATISFY', '_METSTAT',
       'SSBFRUT3', '_TOTINDA', '_IMPRACE', '_RFDRHV9', '_HLTHPL2', '_RACE',
       '_AGEG5YR', '_BMI5', 'ADDEPEV3', 'EMTSUPRT', 'DIABETE4',
       'GENHLTH_LABEL', '_SEX_LABEL', 'PHYSHLTH_LABEL', 'MENTHLTH_LABEL',
       'POORHLTH_LABEL', 'PERSDOC3_LABEL', 'MEDCOST1_LABEL', 'EXERANY2_LABEL',
       'CVDSTRK3_LABEL'],
      dtype='object')

In [414]:
print(df['CHCKDNY2'].unique())
print(df['CHCKDNY2'].value_counts(dropna=False))


[2. 1.]
CHCKDNY2
2.0    425925
1.0     23435
Name: count, dtype: int64


In [415]:
df['CHCKDNY2_LABEL'] = df['CHCKDNY2'].map({
    1: 'Yes',
    2: 'No',
})


In [416]:
df[['CHCKDNY2', 'CHCKDNY2_LABEL']].head()


CHCKDNY2 CHCKDNY2_LABEL
0       2.0             No
1       2.0             No
2       2.0             No
3       2.0             No
4       2.0             No

In [417]:
print(df['MARITAL'].unique())
print(df['MARITAL'].value_counts(dropna=False))


[3. 1. 6. 5. 2. 4.]
MARITAL
1.0    228302
5.0     83647
2.0     58109
3.0     48378
6.0     21562
4.0      9362
Name: count, dtype: int64


In [418]:
df['MARITAL_LABEL'] = df['MARITAL'].map({
    1: 'Married',
    2: 'Divorced',
    3: 'Widowed',
    4: 'Separated',
    5: 'Never married',
    6: 'Unmarried couple',
    9: 'Refused'
})


In [419]:
df[['MARITAL', 'MARITAL_LABEL']].head()


MARITAL     MARITAL_LABEL
0      3.0           Widowed
1      1.0           Married
2      6.0  Unmarried couple
3      1.0           Married
4      5.0     Never married

In [420]:
print(df['EDUCA'].unique())
print(df['EDUCA'].value_counts(dropna=False))


[4. 6. 5. 3. 2. 1.]
EDUCA
6.0    189517
5.0    118725
4.0    114209
3.0     17056
2.0      9152
1.0       701
Name: count, dtype: int64


In [421]:
df['EDUCA_LABEL'] = df['EDUCA'].map({
    1: 'Never attended / Kindergarten',
    2: 'Elementary (Grades 1–8)',
    3: 'Some high school (Grades 9–11)',
    4: 'High school graduate / GED',
    5: 'Some college (1–3 years)',
    6: 'College graduate (4+ years)',
    9: 'Refused'
})


In [422]:
df[['EDUCA', 'EDUCA_LABEL']].head()


EDUCA                  EDUCA_LABEL
0    4.0   High school graduate / GED
1    6.0  College graduate (4+ years)
2    5.0     Some college (1–3 years)
3    6.0  College graduate (4+ years)
4    5.0     Some college (1–3 years)

In [423]:
print(df['EMPLOY1'].unique())
print(df['EMPLOY1'].value_counts(dropna=False))


[7. 1. 8. 5. 2. 6. 3. 4.]
EMPLOY1
1.0    190685
7.0    144338
2.0     38580
8.0     27411
5.0     17551
6.0     11297
4.0     10695
3.0      8803
Name: count, dtype: int64


In [424]:
df['EMPLOY1_LABEL'] = df['EMPLOY1'].map({
    1: 'Employed for wages',
    2: 'Self-employed',
    3: 'Out of work (1+ years)',
    4: 'Out of work (<1 year)',
    5: 'Homemaker',
    6: 'Student',
    7: 'Retired',
    8: 'Unable to work',
})

In [425]:
df[['EMPLOY1', 'EMPLOY1_LABEL']].head()


EMPLOY1       EMPLOY1_LABEL
0      7.0             Retired
1      7.0             Retired
2      1.0  Employed for wages
3      7.0             Retired
4      8.0      Unable to work

In [426]:
print(df['_INCOMG1'].unique())
print(df['_INCOMG1'].value_counts(dropna=False))


[5. 7. 4. 2. 6. 3. 1.]
_INCOMG1
5.0    193776
6.0     81770
4.0     49230
3.0     41310
2.0     33211
7.0     29425
1.0     20638
Name: count, dtype: int64


In [427]:
df['_INCOMG1_LABEL'] = df['_INCOMG1'].map({
    1: '< $10,000',
    2: '$10k–$15k',
    3: '$15k–$20k',
    4: '$20k–$25k',
    5: '$25k–$35k',
    6: '$35k–$50k',
    7: '$50k–$75k',
})


In [428]:
df[['_INCOMG1', '_INCOMG1_LABEL']].head()


_INCOMG1 _INCOMG1_LABEL
0       5.0      $25k–$35k
1       7.0      $50k–$75k
2       5.0      $25k–$35k
3       4.0      $20k–$25k
4       2.0      $10k–$15k

In [429]:

print(df['DIFFWALK'].unique())
print(df['DIFFWALK'].value_counts(dropna=False))


[2. 1.]
DIFFWALK
2.0    378788
1.0     70572
Name: count, dtype: int64


In [430]:
df['DIFFWALK_LABEL'] = df['DIFFWALK'].map({
    1: 'Yes',
    2: 'No'
})


In [431]:
df[['DIFFWALK', 'DIFFWALK_LABEL']].head()


DIFFWALK DIFFWALK_LABEL
0       2.0             No
1       2.0             No
2       2.0             No
3       2.0             No
4       1.0            Yes

In [432]:
print(df['SMOKE100'].unique())
print(df['SMOKE100'].value_counts(dropna=False))


[2. 1.]
SMOKE100
2.0    284279
1.0    165081
Name: count, dtype: int64


In [433]:
df['SMOKE100_LABEL'] = df['SMOKE100'].map({
    1: 'Yes',
    2: 'No'
})


In [434]:
df[['SMOKE100', 'SMOKE100_LABEL']].head()


SMOKE100 SMOKE100_LABEL
0       2.0             No
1       1.0            Yes
2       1.0            Yes
3       2.0             No
4       2.0             No

In [435]:
print(df['LSATISFY'].unique())
print(df['LSATISFY'].value_counts(dropna=False))


[1. 2. 3. 4.]
LSATISFY
2.0    349082
1.0     89127
3.0      8727
4.0      2424
Name: count, dtype: int64


In [436]:
df['LSATISFY_LABEL'] = df['LSATISFY'].map({
    1: 'Very satisfied',
    2: 'Satisfied',
    3: 'Dissatisfied',
    4: 'Very dissatisfied',
})


In [437]:
df[['LSATISFY', 'LSATISFY_LABEL']].head()

LSATISFY  LSATISFY_LABEL
0       1.0  Very satisfied
1       1.0  Very satisfied
2       1.0  Very satisfied
3       1.0  Very satisfied
4       2.0       Satisfied

In [438]:
print(df['_METSTAT'].unique())
print(df['_METSTAT'].value_counts(dropna=False))


[1. 2.]
_METSTAT
1.0    325298
2.0    124062
Name: count, dtype: int64


In [439]:
df['_METSTAT_LABEL'] = df['_METSTAT'].map({
    1: 'Metabolically Healthy',
    2: 'Metabolically At-Risk',
})


In [440]:
df[['_METSTAT', '_METSTAT_LABEL']].head()

_METSTAT         _METSTAT_LABEL
0       1.0  Metabolically Healthy
1       1.0  Metabolically Healthy
2       2.0  Metabolically At-Risk
3       2.0  Metabolically At-Risk
4       1.0  Metabolically Healthy

In [441]:
print(df['SSBFRUT3'].unique())
print(df['SSBFRUT3'].value_counts(dropna=False))


[202. 101. 301. 201. 302. 102. 103. 310. 304. 120. 303. 203. 315. 205.
 305. 330. 112. 106. 105. 204. 107. 104. 320. 312. 131. 114. 309. 130.
 307. 350. 314. 306. 325. 318. 110. 215. 206. 316. 323. 308. 207. 210.
 199. 115. 399. 109. 208. 317. 214. 108. 150. 327. 321. 324. 335. 360.
 328. 340. 211. 329. 225. 230. 128. 125. 221. 153. 242. 212. 124. 322.
 313. 338. 220. 122. 113. 326. 299. 311. 331. 291. 222. 209. 364. 118.
 260. 224. 140. 217. 388. 116. 228. 390. 213.]
SSBFRUT3
202.0    405458
201.0      8744
101.0      6999
301.0      5254
302.0      4784
          ...  
140.0         1
388.0         1
116.0         1
228.0         1
213.0         1
Name: count, Length: 93, dtype: int64


### SSBFRUT3 — Sugar-Sweetened Beverage Frequency Mapping

This variable contains numeric codes representing how often a person consumes sugary drinks.  
We created a new label column by mapping each code to a readable frequency category such as *daily*, *weekly*, *monthly*, or *rare/unknown*.  
Any values not covered in the mapping were grouped under **“Other”**.  
This makes the beverage intake patterns easier to understand and analyze during EDA.


In [442]:
# Mapping numeric codes to readable frequency labels
ssb_mapping = {
    # Daily intake
    101: '1 time/day', 102: '2 times/day', 103: '3 times/day', 104: '4 times/day', 105: '5 times/day',
    106: '6 times/day', 107: '7 times/day', 108: '8+ times/day', 109: '9+ times/day', 110: '10+ times/day',

    # Weekly intake
    201: '1 time/week', 202: '0 times/day', 203: '2 times/week', 204: '3 times/week', 205: '4 times/week',
    206: '5 times/week', 207: '6 times/week', 208: '7 times/week', 210: '8+ times/week',

    # Monthly intake (300+ series)
    301: '1 time/month', 302: '2 times/month', 303: '3 times/month', 304: '4 times/month',
    305: '5 times/month', 306: '6 times/month', 307: '7 times/month', 308: '8 times/month',
    309: '9 times/month', 310: '10+ times/month',

    # Rare or unknown codes
    399: 'Don’t know/refused', 777: 'Not asked', 888: 'Refused', 999: 'Missing'
}

# Apply mapping
df['SSBFRUT3_LABEL'] = df['SSBFRUT3'].map(ssb_mapping)

# Fill anything unmapped as 'Other'
df['SSBFRUT3_LABEL'] = df['SSBFRUT3_LABEL'].fillna('Other')

# Check result
print(df[['SSBFRUT3', 'SSBFRUT3_LABEL']].head())
print(df['SSBFRUT3_LABEL'].value_counts())


   SSBFRUT3 SSBFRUT3_LABEL
0     202.0    0 times/day
1     202.0    0 times/day
2     202.0    0 times/day
3     202.0    0 times/day
4     202.0    0 times/day
SSBFRUT3_LABEL
0 times/day           405458
1 time/week             8744
1 time/day              6999
1 time/month            5254
2 times/month           4784
2 times/day             3252
2 times/week            2599
Other                   2381
3 times/month           1833
5 times/month           1452
4 times/month           1165
3 times/week            1042
10+ times/month          852
3 times/day              811
4 times/week             703
6 times/month            330
4 times/day              314
7 times/month            239
5 times/day              230
6 times/week             215
8 times/month            177
7 times/day              159
5 times/week             101
6 times/day               52
Don’t know/refused        51
8+ times/week             50
10+ times/day             43
7 times/week              29
8+ times/da

In [443]:
# Check result
df[['SSBFRUT3_LABEL', 'SSBFRUT3']].head()

SSBFRUT3_LABEL  SSBFRUT3
0    0 times/day     202.0
1    0 times/day     202.0
2    0 times/day     202.0
3    0 times/day     202.0
4    0 times/day     202.0

In [444]:
print(df['_TOTINDA'].unique())
print(df['_TOTINDA'].describe())

df['_TOTINDA_LABEL'] = df['_TOTINDA'].map({
    1: '1 adult',
    2: '2 adults'
})

# Check result
df[['_TOTINDA_LABEL', '_TOTINDA']].head()

[1. 2.]
count    449360.000000
mean          1.232829
std           0.422635
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           2.000000
Name: _TOTINDA, dtype: float64


_TOTINDA_LABEL  _TOTINDA
0        1 adult       1.0
1        1 adult       1.0
2        1 adult       1.0
3        1 adult       1.0
4       2 adults       2.0

In [445]:
# 1️ Check unique values and summary
print(df['_IMPRACE'].unique())
print(df['_IMPRACE'].describe())



[1. 6. 2. 3. 5. 4.]
count    449360.000000
mean          1.791310
std           1.528474
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max           6.000000
Name: _IMPRACE, dtype: float64


In [446]:

#  Map numeric codes to readable labels
df['_IMPRACE_LABEL'] = df['_IMPRACE'].map({
    1: 'White',
    2: 'Black',
    3: 'American Indian/Alaska Native',
    4: 'Asian',
    5: 'Native Hawaiian/Pacific Islander',
})

#  Check result
df[['_IMPRACE_LABEL', '_IMPRACE']].head()
df['_IMPRACE_LABEL'].value_counts()

_IMPRACE_LABEL
White                               330653
Native Hawaiian/Pacific Islander     48489
Black                                34781
American Indian/Alaska Native        12455
Asian                                 6487
Name: count, dtype: int64

In [447]:
# 1️ Check unique values and summary
print(df['_HLTHPL2'].unique())
print(df['_HLTHPL2'].value_counts())




[1. 2.]
_HLTHPL2
1.0    424291
2.0     25069
Name: count, dtype: int64


In [448]:
# Map numeric codes to labels
df['_HLTHPL2_LABEL'] = df['_HLTHPL2'].map({
    1: 'Has health plan',
    2: 'No health plan'
})

print(df['_HLTHPL2'].unique())
print(df['_HLTHPL2'].value_counts())


[1. 2.]
_HLTHPL2
1.0    424291
2.0     25069
Name: count, dtype: int64


In [449]:
#  Check unique values
print(df['_RACE'].unique())
print(df['_RACE'].value_counts(dropna=False))


[1. 7. 2. 4. 8. 6. 3. 5.]
_RACE
1.0    332008
8.0     48240
2.0     34435
4.0     12361
7.0     10342
3.0      6339
6.0      3604
5.0      2031
Name: count, dtype: int64


In [450]:
#  Map numeric codes to labels
df['_RACE_LABEL'] = df['_RACE'].map({
    1: 'White',
    2: 'Black',
    3: 'American Indian/Alaska Native',
    4: 'Asian',
    5: 'Native Hawaiian/Pacific Islander',
    6: 'Other'
})

#  Check results
df[['_RACE', '_RACE_LABEL']].head()
df['_RACE_LABEL'].value_counts()

_RACE_LABEL
White                               332008
Black                                34435
Asian                                12361
American Indian/Alaska Native         6339
Other                                 3604
Native Hawaiian/Pacific Islander      2031
Name: count, dtype: int64

In [451]:
# DROP THE _RACE LATER 

In [452]:
#  Check unique values
print(df['_AGEG5YR'].unique())
print(df['_AGEG5YR'].value_counts(dropna=False))

[12. 13.  8.  6.  7. 11. 10.  9.  1.  5.  4.  2.  3.]
_AGEG5YR
10.0    47701
11.0    44774
9.0     43387
13.0    41756
12.0    36803
8.0     34936
7.0     31698
5.0     30899
1.0     29692
6.0     28968
4.0     28804
3.0     26237
2.0     23705
Name: count, dtype: int64


In [453]:
# Map numeric codes to readable labels
df['_AGEG5YR_LABEL'] = df['_AGEG5YR'].map({
    1: '18–24',
    2: '25–29',
    3: '30–34',
    4: '35–39',
    5: '40–44',
    6: '45–49',
    7: '50–54',
    8: '55–59',
    9: '60–64',
    10: '65–69',
    11: '70–74',
    12: '75–79',
    13: '80–84'
})

#  Check result
df[['_AGEG5YR', '_AGEG5YR_LABEL']].head()
df['_AGEG5YR_LABEL'].value_counts()

_AGEG5YR_LABEL
65–69    47701
70–74    44774
60–64    43387
80–84    41756
75–79    36803
55–59    34936
50–54    31698
40–44    30899
18–24    29692
45–49    28968
35–39    28804
30–34    26237
25–29    23705
Name: count, dtype: int64

In [454]:
# Check unique values and basic stats
print(df['_BMI5'].unique()[:20])  # first 20 unique for view
print(df['_BMI5'].describe())

[2249. 2583. 2253. 2509. 1977. 3336. 3147. 3649. 4121. 2129. 2510. 2441.
 2740. 2502. 2506. 2962. 2343. 3018. 2912. 2500.]
count    449360.000000
mean       2847.259812
std         630.483530
min        1200.000000
25%        2441.000000
50%        2744.000000
75%        3125.000000
max        9984.000000
Name: _BMI5, dtype: float64


In [455]:
 # Convert to actual BMI
df['_BMI5_ACTUAL'] = df['_BMI5'] / 100

In [456]:
#  Check updated values
df[['_BMI5', '_BMI5_ACTUAL']].head()


_BMI5  _BMI5_ACTUAL
0  2249.0         22.49
1  2583.0         25.83
2  2253.0         22.53
3  2509.0         25.09
4  1977.0         19.77

In [457]:
df['_BMI5_ACTUAL'].describe()

count    449360.000000
mean         28.472598
std           6.304835
min          12.000000
25%          24.410000
50%          27.440000
75%          31.250000
max          99.840000
Name: _BMI5_ACTUAL, dtype: float64

In [458]:
# 1️ Check unique values
print(df['ADDEPEV3'].unique())
print(df['ADDEPEV3'].value_counts(dropna=False))

[2. 1.]
ADDEPEV3
2.0    354189
1.0     95171
Name: count, dtype: int64


In [459]:
#  Add readable label
df['ADDEPEV3_LABEL'] = df['ADDEPEV3'].map({
    1: 'Yes', 
    2: 'No'})

#  Check result

df['ADDEPEV3_LABEL'].value_counts()


ADDEPEV3_LABEL
No     354189
Yes     95171
Name: count, dtype: int64

In [460]:
df[['ADDEPEV3', 'ADDEPEV3_LABEL']].head()

ADDEPEV3 ADDEPEV3_LABEL
0       2.0             No
1       2.0             No
2       2.0             No
3       2.0             No
4       2.0             No

In [461]:
# Check unique values
print(df['EMTSUPRT'].unique())
print(df['EMTSUPRT'].value_counts(dropna=False))


[1. 2. 4. 5. 3.]
EMTSUPRT
1.0    346683
2.0     59155
3.0     26731
4.0      8562
5.0      8229
Name: count, dtype: int64


In [462]:

# Add readable label
df['EMTSUPRT_LABEL'] = df['EMTSUPRT'].map({
    1: 'Always',
    2: 'Usually',
    3: 'Sometimes',
    4: 'Rarely',
    5: 'Never'
})

#  Check result

df['EMTSUPRT_LABEL'].value_counts()


EMTSUPRT_LABEL
Always       346683
Usually       59155
Sometimes     26731
Rarely         8562
Never          8229
Name: count, dtype: int64

In [463]:
df[['EMTSUPRT', 'EMTSUPRT_LABEL']].head() #Indicates how often the respondent gets the social and emotional support they need.

EMTSUPRT EMTSUPRT_LABEL
0       1.0         Always
1       1.0         Always
2       2.0        Usually
3       1.0         Always
4       4.0         Rarely

In [464]:
# Check unique values
print(df['_RFDRHV9'].unique())
print(df['_RFDRHV9'].value_counts(dropna=False))

[1. 2.]
_RFDRHV9
1.0    425412
2.0     23948
Name: count, dtype: int64


In [465]:
# Map numeric codes to readable labels
df['_RFDRHV9_LABEL'] = df['_RFDRHV9'].map({
    1: 'Not heavy drinker',
    2: 'Heavy drinker'
})

# Check results
df[['_RFDRHV9', '_RFDRHV9_LABEL']].head()


_RFDRHV9     _RFDRHV9_LABEL
0       1.0  Not heavy drinker
1       1.0  Not heavy drinker
2       1.0  Not heavy drinker
3       1.0  Not heavy drinker
4       1.0  Not heavy drinker

In [466]:
df['_RFDRHV9_LABEL'].value_counts()

_RFDRHV9_LABEL
Not heavy drinker    425412
Heavy drinker         23948
Name: count, dtype: int64

In [467]:
# -- Check unique values
print(df['DIABETE4'].unique())
print(df['DIABETE4'].value_counts(dropna=False))

[3. 1. 4. 2.]
DIABETE4
3.0    370009
1.0     64821
4.0     11187
2.0      3343
Name: count, dtype: int64


In [468]:
# Add readable label
df['DIABETE4_LABEL'] = df['DIABETE4'].map({
    1: 'Yes',
    2: 'No',
    3: 'Yes, during pregnancy',
    4: 'Pre-diabetes'
})

#  Check result
df[['DIABETE4', 'DIABETE4_LABEL']].head()


DIABETE4         DIABETE4_LABEL
0       3.0  Yes, during pregnancy
1       3.0  Yes, during pregnancy
2       3.0  Yes, during pregnancy
3       3.0  Yes, during pregnancy
4       3.0  Yes, during pregnancy

In [469]:
df['DIABETE4_LABEL'].value_counts()

DIABETE4_LABEL
Yes, during pregnancy    370009
Yes                       64821
Pre-diabetes              11187
No                         3343
Name: count, dtype: int64

In [470]:
# # Create a new DataFrame with only the "_LABEL" columns
# df_labels = df[[col for col in df.columns if '_LABEL' in col]]

# # Check the head
# df_labels.head()


### Creating the Final Labeled Dataset

A new dataset was created by selecting only the important original variables along with all their mapped or binned label columns. These columns were combined into a new DataFrame to ensure every feature is clean, readable, and ready for analysis or modeling. Finally, the labeled dataset was exported as **CLEANED_LABELED_BRFSS2024.csv** for further use.


In [471]:
df.shape

(449360, 58)

In [472]:
df.columns

Index(['GENHLTH', '_SEX', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PERSDOC3',
       'MEDCOST1', 'EXERANY2', 'CVDSTRK3', 'CHCKDNY2', 'MARITAL', 'EDUCA',
       'EMPLOY1', '_INCOMG1', 'DIFFWALK', 'SMOKE100', 'LSATISFY', '_METSTAT',
       'SSBFRUT3', '_TOTINDA', '_IMPRACE', '_RFDRHV9', '_HLTHPL2', '_RACE',
       '_AGEG5YR', '_BMI5', 'ADDEPEV3', 'EMTSUPRT', 'DIABETE4',
       'GENHLTH_LABEL', '_SEX_LABEL', 'PHYSHLTH_LABEL', 'MENTHLTH_LABEL',
       'POORHLTH_LABEL', 'PERSDOC3_LABEL', 'MEDCOST1_LABEL', 'EXERANY2_LABEL',
       'CVDSTRK3_LABEL', 'CHCKDNY2_LABEL', 'MARITAL_LABEL', 'EDUCA_LABEL',
       'EMPLOY1_LABEL', '_INCOMG1_LABEL', 'DIFFWALK_LABEL', 'SMOKE100_LABEL',
       'LSATISFY_LABEL', '_METSTAT_LABEL', 'SSBFRUT3_LABEL', '_TOTINDA_LABEL',
       '_IMPRACE_LABEL', '_HLTHPL2_LABEL', '_RACE_LABEL', '_AGEG5YR_LABEL',
       '_BMI5_ACTUAL', 'ADDEPEV3_LABEL', 'EMTSUPRT_LABEL', '_RFDRHV9_LABEL',
       'DIABETE4_LABEL'],
      dtype='object')

In [474]:
# List of columns to include
columns_to_save = ['GENHLTH', '_SEX', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PERSDOC3',
       'MEDCOST1', 'EXERANY2', 'CVDSTRK3', 'CHCKDNY2', 'MARITAL', 'EDUCA',
       'EMPLOY1', '_INCOMG1', 'DIFFWALK', 'SMOKE100', 'LSATISFY', '_METSTAT',
       'SSBFRUT3', '_TOTINDA', '_IMPRACE', '_RFDRHV9', '_HLTHPL2', '_RACE',
       '_AGEG5YR', '_BMI5', 'ADDEPEV3', 'EMTSUPRT', 'DIABETE4',
       'GENHLTH_LABEL', '_SEX_LABEL', 'PHYSHLTH_LABEL', 'MENTHLTH_LABEL',
       'POORHLTH_LABEL', 'PERSDOC3_LABEL', 'MEDCOST1_LABEL', 'EXERANY2_LABEL',
       'CVDSTRK3_LABEL', 'CHCKDNY2_LABEL', 'MARITAL_LABEL', 'EDUCA_LABEL',
       'EMPLOY1_LABEL', '_INCOMG1_LABEL', 'DIFFWALK_LABEL', 'SMOKE100_LABEL',
       'LSATISFY_LABEL', '_METSTAT_LABEL', 'SSBFRUT3_LABEL', '_TOTINDA_LABEL',
       '_IMPRACE_LABEL', '_HLTHPL2_LABEL', '_RACE_LABEL', '_AGEG5YR_LABEL',
       '_BMI5_ACTUAL', 'ADDEPEV3_LABEL', 'EMTSUPRT_LABEL', '_RFDRHV9_LABEL',
       'DIABETE4_LABEL'
]

# Create new DataFrame with only labeled/binned columns
label_df = df[columns_to_save].copy()

# Save as CSV
label_df.to_csv("CLEANED_LABELED_BRFSS2024.csv", index=False)


In [475]:

# Optional: Check the first few rows
label_df.head()


GENHLTH  _SEX  PHYSHLTH  MENTHLTH  POORHLTH  PERSDOC3  MEDCOST1  EXERANY2  \
0      3.0   2.0       2.0       7.0       7.0       2.0       2.0       1.0   
1      1.0   1.0       6.0       7.0       7.0       1.0       2.0       1.0   
2      2.0   1.0      30.0       7.0       1.0       3.0       1.0       1.0   
3      1.0   1.0       6.0       7.0       7.0       1.0       2.0       1.0   
4      3.0   1.0       6.0       7.0       7.0       1.0       2.0       2.0   

   CVDSTRK3  CHCKDNY2  ...  _TOTINDA_LABEL  _IMPRACE_LABEL   _HLTHPL2_LABEL  \
0       2.0       2.0  ...         1 adult           White  Has health plan   
1       2.0       2.0  ...         1 adult           White  Has health plan   
2       2.0       2.0  ...         1 adult           White  Has health plan   
3       2.0       2.0  ...         1 adult           White  Has health plan   
4       2.0       2.0  ...        2 adults           White  Has health plan   

   _RACE_LABEL  _AGEG5YR_LABEL  _BMI5_ACTUAL  ADDEPEV3_LABEL  EMTSUPRT_LABEL  \
0        White           75–79         22.49              No          Always   
1        White           80–84         25.83              No          Always   
2        White           55–59         22.53              No         Usually   
3        White           80–84         25.09              No          Always   
4        White           45–49         19.77              No          Rarely   

      _RFDRHV9_LABEL         DIABETE4_LABEL  
0  Not heavy drinker  Yes, during pregnancy  
1  Not heavy drinker  Yes, during pregnancy  
2  Not heavy drinker  Yes, during pregnancy  
3  Not heavy drinker  Yes, during pregnancy  
4  Not heavy drinker  Yes, during pregnancy  

[5 rows x 58 columns]