## PROJECT - Classifying Diabetes Risk Using Machine Learning On BRFSS 2024 Data 

`Stpe 2: Data cleaning and feature selection`

### Import the data which we saved in Step 1 whihc was converted from XPT TO CSV

In [39]:
# step 1 Import the libraries required

In [40]:
#Import the liabaries 
import pandas as pd
import numpy as np

In [41]:
# data loading

In [42]:
brfss = pd.read_csv(r"C:\Users\Junaid\Documents\RM_models_Data\BRFSS_2024.csv")

In [43]:
brfss.head()

_STATE  FMONTH        IDATE IMONTH   IDAY    IYEAR  DISPCODE  \
0     1.0     2.0  b'02282024'  b'02'  b'28'  b'2024'    1100.0   
1     1.0     2.0  b'02212024'  b'02'  b'21'  b'2024'    1100.0   
2     1.0     2.0  b'02212024'  b'02'  b'21'  b'2024'    1100.0   
3     1.0     2.0  b'02282024'  b'02'  b'28'  b'2024'    1100.0   
4     1.0     2.0  b'02212024'  b'02'  b'21'  b'2024'    1100.0   

           SEQNO          _PSU  CTELENM1  PVTRESD1  COLGHOUS  STATERE1  \
0  b'2024000001'  2.024000e+09       1.0       1.0       NaN       1.0   
1  b'2024000002'  2.024000e+09       1.0       1.0       NaN       1.0   
2  b'2024000003'  2.024000e+09       1.0       1.0       NaN       1.0   
3  b'2024000004'  2.024000e+09       1.0       1.0       NaN       1.0   
4  b'2024000005'  2.024000e+09       1.0       1.0       NaN       1.0   

   CELPHON1  LADULT1  NUMADULT  RESPSLC1  LANDSEX3  SAFETIME  CTELNUM1  \
0       2.0      1.0       1.0       NaN       2.0       NaN       NaN   
1       2.0      1.0       2.0       1.0       1.0       NaN       NaN   
2       2.0      1.0       3.0       1.0       1.0       NaN       NaN   
3       2.0      1.0       1.0       NaN       1.0       NaN       NaN   
4       2.0      1.0       3.0       1.0       1.0       NaN       NaN   

   CELLFON5  CADULT1  CELLSEX3  PVTRESD3  CCLGHOUS  CSTATE1  LANDLINE  \
0       NaN      NaN       NaN       NaN       NaN      NaN       NaN   
1       NaN      NaN       NaN       NaN       NaN      NaN       NaN   
2       NaN      NaN       NaN       NaN       NaN      NaN       NaN   
3       NaN      NaN       NaN       NaN       NaN      NaN       NaN   
4       NaN      NaN       NaN       NaN       NaN      NaN       NaN   

   HHADULT  SEXVAR  GENHLTH  PHYSHLTH  MENTHLTH  POORHLTH  PRIMINS2  PERSDOC3  \
0      NaN     2.0      3.0       2.0      88.0      88.0       3.0       2.0   
1      NaN     1.0      1.0      88.0      88.0       NaN       3.0       1.0   
2      NaN     1.0      2.0      30.0      88.0       1.0       1.0       3.0   
3      NaN     1.0      1.0      88.0      88.0       NaN       3.0       1.0   
4      NaN     1.0      3.0      88.0      88.0       NaN       5.0       1.0   

   MEDCOST1  CHECKUP1  EXERANY2  LASTDEN4  RMVTETH4  CVDINFR4  CVDCRHD4  \
0       2.0       1.0       1.0       1.0       1.0       2.0       2.0   
1       2.0       1.0       1.0       1.0       1.0       2.0       1.0   
2       1.0       4.0       1.0       4.0       2.0       2.0       2.0   
3       2.0       1.0       1.0       1.0       8.0       2.0       2.0   
4       2.0       1.0       2.0       1.0       1.0       2.0       2.0   

   CVDSTRK3  ASTHMA3  ASTHNOW  CHCSCNC1  CHCOCNC1  CHCCOPD3  ADDEPEV3  \
0       2.0      2.0      NaN       1.0       2.0       2.0       2.0   
1       2.0      2.0      NaN       2.0       2.0       2.0       2.0   
2       2.0      2.0      NaN       2.0       2.0       2.0       2.0   
3       2.0      2.0      NaN       1.0       2.0       2.0       2.0   
4       2.0      2.0      NaN       2.0       2.0       2.0       2.0   

   CHCKDNY2  HAVARTH4  DIABETE4  DIABAGE4  MARITAL  EDUCA  RENTHOM1  NUMHHOL4  \
0       2.0       1.0       3.0       NaN      3.0    4.0       1.0       2.0   
1       2.0       1.0       3.0       NaN      1.0    6.0       1.0       2.0   
2       2.0       1.0       3.0       NaN      6.0    5.0       1.0       2.0   
3       2.0       1.0       3.0       NaN      1.0    6.0       1.0       2.0   
4       2.0       2.0       3.0       NaN      5.0    5.0       1.0       2.0   

   NUMPHON4  CPDEMO1C  VETERAN3  EMPLOY1  CHILDREN  INCOME3  PREGNANT  \
0       NaN       1.0       2.0      7.0      88.0     99.0       NaN   
1       NaN       1.0       1.0      7.0      88.0     11.0       NaN   
2       NaN       8.0       1.0      1.0      88.0     99.0       NaN   
3       NaN       1.0       2.0      7.0      88.0      6.0       NaN   
4       NaN       1.0       2.0      8.0  

###  Inspecting Raw Columns  
Before starting data cleaning or feature engineering, it is important to view all the original columns present in the BRFSS dataset.  
This helps in:
- selecting relatable columns
- Understanding what variables are available  
- Identifying which columns require cleaning  
- Planning feature engineering  


In [44]:
# to get all the columns head we are using function set_option()
pd.set_option("display.max_columns", None)

In [45]:
brfss.shape

(457670, 301)

In [100]:
brfss.info

<bound method DataFrame.info of         _STATE  FMONTH        IDATE IMONTH   IDAY    IYEAR  DISPCODE  \
0          1.0     2.0  b'02282024'  b'02'  b'28'  b'2024'    1100.0   
1          1.0     2.0  b'02212024'  b'02'  b'21'  b'2024'    1100.0   
2          1.0     2.0  b'02212024'  b'02'  b'21'  b'2024'    1100.0   
3          1.0     2.0  b'02282024'  b'02'  b'28'  b'2024'    1100.0   
4          1.0     2.0  b'02212024'  b'02'  b'21'  b'2024'    1100.0   
...        ...     ...          ...    ...    ...      ...       ...   
457665    78.0     7.0  b'07122024'  b'07'  b'12'  b'2024'    1200.0   
457666    78.0     7.0  b'07182024'  b'07'  b'18'  b'2024'    1100.0   
457667    78.0     7.0  b'07172024'  b'07'  b'17'  b'2024'    1100.0   
457668    78.0     7.0  b'07202024'  b'07'  b'20'  b'2024'    1200.0   
457669    78.0     7.0  b'07182024'  b'07'  b'18'  b'2024'    1100.0   

                SEQNO          _PSU  CTELENM1  PVTRESD1  COLGHOUS  STATERE1  \
0       b'2024000001'  2

In [47]:
brfss.columns.tolist() #these are the raw columns, which we  to select have select according to task.

['_STATE',
 'FMONTH',
 'IDATE',
 'IMONTH',
 'IDAY',
 'IYEAR',
 'DISPCODE',
 'SEQNO',
 '_PSU',
 'CTELENM1',
 'PVTRESD1',
 'COLGHOUS',
 'STATERE1',
 'CELPHON1',
 'LADULT1',
 'NUMADULT',
 'RESPSLC1',
 'LANDSEX3',
 'SAFETIME',
 'CTELNUM1',
 'CELLFON5',
 'CADULT1',
 'CELLSEX3',
 'PVTRESD3',
 'CCLGHOUS',
 'CSTATE1',
 'LANDLINE',
 'HHADULT',
 'SEXVAR',
 'GENHLTH',
 'PHYSHLTH',
 'MENTHLTH',
 'POORHLTH',
 'PRIMINS2',
 'PERSDOC3',
 'MEDCOST1',
 'CHECKUP1',
 'EXERANY2',
 'LASTDEN4',
 'RMVTETH4',
 'CVDINFR4',
 'CVDCRHD4',
 'CVDSTRK3',
 'ASTHMA3',
 'ASTHNOW',
 'CHCSCNC1',
 'CHCOCNC1',
 'CHCCOPD3',
 'ADDEPEV3',
 'CHCKDNY2',
 'HAVARTH4',
 'DIABETE4',
 'DIABAGE4',
 'MARITAL',
 'EDUCA',
 'RENTHOM1',
 'NUMHHOL4',
 'NUMPHON4',
 'CPDEMO1C',
 'VETERAN3',
 'EMPLOY1',
 'CHILDREN',
 'INCOME3',
 'PREGNANT',
 'WEIGHT2',
 'HEIGHT3',
 'DEAF',
 'BLIND',
 'DECIDE',
 'DIFFWALK',
 'DIFFDRES',
 'DIFFALON',
 'HADMAM',
 'HOWLONG',
 'CERVSCRN',
 'CRVCLCNC',
 'CRVCLPAP',
 'CRVCLHPV',
 'HADHYST2',
 'HADSIGM4',
 'COLNSIGM',

### 📌 Selecting Relevant Columns for Analysis  
From the full BRFSS dataset, a subset of important variables is selected for analysis and modeling.  
These columns include:
- Demographics (age group, sex, race, education, income)
- Health indicators (BMI, general health, physical/mental health days)
- Lifestyle factors (exercise, smoking, sugary drink intake)
- Access to care (personal doctor, medical cost issues, health plan)
- Chronic conditions (stroke, kidney disease, diabetes)
- Additional behavioral/psychosocial factors (life satisfaction, emotional support)

This selection reduces noise, improves manageability, and focuses on variables relevant to health outcomes and diabetes prediction.


In [48]:
selected_df = brfss[[
    "GENHLTH",
    "_SEX",
    "PHYSHLTH",
    "MENTHLTH",
    "POORHLTH",
    "PERSDOC3",
    "MEDCOST1",
    "EXERANY2",
    "CVDSTRK3",
    "CHCKDNY2",
    "MARITAL",
    "EDUCA",
    "EMPLOY1",
    "_INCOMG1",
    "DIFFWALK",
    "SMOKE100",
    "LSATISFY",
    "_METSTAT",
    "SSBFRUT3",
    "_TOTINDA",
    "_IMPRACE",
    '_RFDRHV9',
    "_HLTHPL2",
    "_RACE",
    "_AGEG5YR",
    "_BMI5",
    'ADDEPEV3',
    'EMTSUPRT',
    '_RFDRHV9',
    "DIABETE4"
]]

###  Creating a Working Copy of the Selected Dataset  🗂️
A separate working copy of the selected columns is created to ensure that the original selection remains untouched.  
This allows safe experimentation during cleaning, preprocessing, and feature engineering without altering the original subset.


In [49]:
df = selected_df.copy()

In [50]:
df.head()

GENHLTH  _SEX  PHYSHLTH  MENTHLTH  POORHLTH  PERSDOC3  MEDCOST1  EXERANY2  \
0      3.0   2.0       2.0      88.0      88.0       2.0       2.0       1.0   
1      1.0   1.0      88.0      88.0       NaN       1.0       2.0       1.0   
2      2.0   1.0      30.0      88.0       1.0       3.0       1.0       1.0   
3      1.0   1.0      88.0      88.0       NaN       1.0       2.0       1.0   
4      3.0   1.0      88.0      88.0       NaN       1.0       2.0       2.0   

   CVDSTRK3  CHCKDNY2  MARITAL  EDUCA  EMPLOY1  _INCOMG1  DIFFWALK  SMOKE100  \
0       2.0       2.0      3.0    4.0      7.0       9.0       2.0       2.0   
1       2.0       2.0      1.0    6.0      7.0       7.0       2.0       1.0   
2       2.0       2.0      6.0    5.0      1.0       9.0       2.0       1.0   
3       2.0       2.0      1.0    6.0      7.0       4.0       2.0       2.0   
4       2.0       2.0      5.0    5.0      8.0       2.0       1.0       2.0   

   LSATISFY  _METSTAT  SSBFRUT3  _TOTINDA  _IMPRACE  _RFDRHV9  _HLTHPL2  \
0       1.0       1.0       NaN       1.0       1.0       1.0       1.0   
1       1.0       1.0       NaN       1.0       1.0       1.0       1.0   
2       1.0       2.0       NaN       1.0       1.0       1.0       1.0   
3       1.0       2.0       NaN       1.0       1.0       1.0       1.0   
4       2.0       1.0       NaN       2.0       1.0       1.0       1.0   

   _RACE  _AGEG5YR   _BMI5  ADDEPEV3  EMTSUPRT  _RFDRHV9  DIABETE4  
0    1.0      12.0  2249.0       2.0       1.0       1.0       3.0  
1    1.0      13.0  2583.0       2.0       1.0       1.0       3.0  
2    1.0       8.0  2253.0       2.0       2.0       1.0       3.0  
3    1.0      13.0  2509.0       2.0       1.0       1.0       3.0  
4    1.0       6.0  1977.0       2.0       4.0       1.0       3.0

#### now we can see that we have 30 relatable features for diabetes classification model

In [51]:
df.shape

(457670, 30)

# A. Data Cleaning

#### checking Missing values in the columns 

In [52]:
df.isna().sum()

GENHLTH          5
_SEX             0
PHYSHLTH         5
MENTHLTH         3
POORHLTH    189421
PERSDOC3         3
MEDCOST1         6
EXERANY2         3
CVDSTRK3         3
CHCKDNY2         6
MARITAL          9
EDUCA            7
EMPLOY1       3303
_INCOMG1         0
DIFFWALK     18672
SMOKE100     28860
LSATISFY    253906
_METSTAT     14623
SSBFRUT3    342354
_TOTINDA         0
_IMPRACE         0
_RFDRHV9         0
_HLTHPL2         0
_RACE            0
_AGEG5YR         0
_BMI5        43037
ADDEPEV3         5
EMTSUPRT    254208
_RFDRHV9         0
DIABETE4         4
dtype: int64

#### Observation:
- Some variables have very low missing values (eg. GENHLTH, MENTHLTH, SEX).
- A few variables have extremely high missing values (eg. LSATISFY, SSBFRUT3, EMTSUPRT, POORHLTH).
- missing value may require filling,  that is only choice left becuase those columns are important for analysis.
This step helps ensure clean, reliable data before modeling.

In [53]:
# Calculate missing values as percentage
missing_percentage = df.isna().sum() / len(df) * 100

# Display
print(missing_percentage)

GENHLTH      0.001092
_SEX         0.000000
PHYSHLTH     0.001092
MENTHLTH     0.000655
POORHLTH    41.388118
PERSDOC3     0.000655
MEDCOST1     0.001311
EXERANY2     0.000655
CVDSTRK3     0.000655
CHCKDNY2     0.001311
MARITAL      0.001966
EDUCA        0.001529
EMPLOY1      0.721699
_INCOMG1     0.000000
DIFFWALK     4.079795
SMOKE100     6.305854
LSATISFY    55.477964
_METSTAT     3.195097
SSBFRUT3    74.803680
_TOTINDA     0.000000
_IMPRACE     0.000000
_RFDRHV9     0.000000
_HLTHPL2     0.000000
_RACE        0.000000
_AGEG5YR     0.000000
_BMI5        9.403500
ADDEPEV3     0.001092
EMTSUPRT    55.543951
_RFDRHV9     0.000000
DIABETE4     0.000874
dtype: float64


In [57]:
for col in df.columns:
    print(f"{col}: {df[col]}.unique()\n") # _RFDRHV9 selected two times so will remove it later! 

GENHLTH: 0         3.0
1         1.0
2         2.0
3         1.0
4         3.0
         ... 
457665    7.0
457666    4.0
457667    3.0
457668    1.0
457669    3.0
Name: GENHLTH, Length: 457670, dtype: float64.unique()

_SEX: 0         2.0
1         1.0
2         1.0
3         1.0
4         1.0
         ... 
457665    1.0
457666    1.0
457667    1.0
457668    1.0
457669    1.0
Name: _SEX, Length: 457670, dtype: float64.unique()

PHYSHLTH: 0          2.0
1         88.0
2         30.0
3         88.0
4         88.0
          ... 
457665    77.0
457666     5.0
457667    88.0
457668    88.0
457669    30.0
Name: PHYSHLTH, Length: 457670, dtype: float64.unique()

MENTHLTH: 0         88.0
1         88.0
2         88.0
3         88.0
4         88.0
          ... 
457665     2.0
457666     1.0
457667    88.0
457668    88.0
457669    88.0
Name: MENTHLTH, Length: 457670, dtype: float64.unique()

POORHLTH: 0         88.0
1          NaN
2          1.0
3          NaN
4          NaN
          ... 
4576

# Looping through each column to display all unique values present.
 This helps identify:
 - Invalid or special codes (e.g., 7 = Don't know, 9 = Refused)
 - Out-of-range values
 - Categories that need grouping or recoding
 Useful for planning the next steps in data cleaning and encoding.

In [56]:

for col in df.columns:
    print(f"{col}:\n{df[col].value_counts()}\n")
# _RFDRHV9 selected two times so will remove it later! 

GENHLTH:
GENHLTH
3.0    156229
2.0    145791
4.0     67919
1.0     64217
5.0     22204
7.0       915
9.0       390
Name: count, dtype: int64

_SEX:
_SEX
2.0    240163
1.0    217507
Name: count, dtype: int64

PHYSHLTH:
PHYSHLTH
88.0    267576
30.0     36353
2.0      27903
1.0      18505
3.0      16919
5.0      16155
10.0     11130
15.0      9805
7.0       9385
4.0       9023
77.0      8765
20.0      6492
14.0      4667
6.0       2495
25.0      2494
99.0      2297
8.0       1856
12.0      1120
21.0       982
28.0       897
9.0        418
29.0       411
18.0       343
16.0       299
27.0       246
22.0       209
17.0       198
13.0       156
26.0       139
11.0       135
24.0       118
23.0       117
19.0        57
Name: count, dtype: int64

MENTHLTH:
MENTHLTH
88.0    269909
30.0     27295
2.0      25180
5.0      21369
10.0     16465
3.0      15961
1.0      15412
15.0     15317
20.0      9721
4.0       8381
7.0       8277
77.0      5594
25.0      3346
14.0      2847
99.0      2559
6.0    

ValueError: Grouper for '_RFDRHV9' not 1-dimensional

### 🛠️ Cleaning Invalid Codes and Handling Missing Values  

Several BRFSS variables contain special numeric codes such as **77, 88, and 99**, which represent:
- *77 = Don't know / Not sure*  
- *88 = None / No days*  
- *99 = Refused / Missing information*  

The important thing is these codes are not actual data values and must be treated as missing values.

#### ✔ Steps Performed:
1. **Checked unique values** for each variable to identify the presence of invalid codes.  
2. **Replaced invalid codes (77, 88, 99)** with `NaN` to ensure consistency in missing-value handling.  
3. **Filled missing values using appropriate imputation methods** such as:
   - **Mode** for categorical variables, there are more binary values so mode is suitable
   - **Median** for numerical variables    
4. **Re-checked updated values** to confirm that invalid codes were removed and replaced correctly.

This approach prevents unnecessary loss of data, especially since dropping all rows with NaN would significantly reduce the dataset size. Imputing missing values maintains dataset integrity and supports better model performance.


In [58]:
# 1️ Check unique values (including NaN)
print(df['GENHLTH'].unique())

# 2️ Replace invalid codes with NaN
df['GENHLTH'] = df['GENHLTH'].replace([7, 9], np.nan)


# 3️ Fill NaN with mode (most frequent value)
df['GENHLTH'] = df['GENHLTH'].fillna(df['GENHLTH'].mode()[0])

#  Check updated values
print(df['GENHLTH'].value_counts(dropna=False))
print(df['GENHLTH'].unique())

[ 3.  1.  2.  4.  5.  7.  9. nan]
GENHLTH
3.0    157539
2.0    145791
4.0     67919
1.0     64217
5.0     22204
Name: count, dtype: int64
[3. 1. 2. 4. 5.]


In [59]:
# 1️ Check unique values (including NaN)
print(df['PHYSHLTH'].unique())

# 2️ Replace invalid codes with NaN
df['PHYSHLTH'] = df['PHYSHLTH'].replace([77, 88, 99], np.nan)

# 3️ Fill NaN with median (this is a numeric "days" variable)
df['PHYSHLTH'] = df['PHYSHLTH'].fillna(df['PHYSHLTH'].median())

#  Check updated values
print(df['PHYSHLTH'].value_counts(dropna=False))
print(df['PHYSHLTH'].unique())


[ 2. 88. 30.  7.  5. 14.  1. 99. 25. 20. 77.  6.  3.  4. 15. 10.  8. 27.
 12. 29. 28. 21.  9. 19. 16. 23. 18. 17. 26. 24. 11. 22. 13. nan]
PHYSHLTH
6.0     281138
30.0     36353
2.0      27903
1.0      18505
3.0      16919
5.0      16155
10.0     11130
15.0      9805
7.0       9385
4.0       9023
20.0      6492
14.0      4667
25.0      2494
8.0       1856
12.0      1120
21.0       982
28.0       897
9.0        418
29.0       411
18.0       343
16.0       299
27.0       246
22.0       209
17.0       198
13.0       156
26.0       139
11.0       135
24.0       118
23.0       117
19.0        57
Name: count, dtype: int64
[ 2.  6. 30.  7.  5. 14.  1. 25. 20.  3.  4. 15. 10.  8. 27. 12. 29. 28.
 21.  9. 19. 16. 23. 18. 17. 26. 24. 11. 22. 13.]


In [60]:
# 1️ Check unique values (including NaN)
print(df['MENTHLTH'].unique())

# 2️ Replace invalid codes with NaN
df['MENTHLTH'] = df['MENTHLTH'].replace([77, 88, 99], np.nan)

# 3️ Fill NaN with median (numeric "days" variable)
df['MENTHLTH'] = df['MENTHLTH'].fillna(df['MENTHLTH'].median())

#  Check updated values
print(df['MENTHLTH'].value_counts(dropna=False))
print(df['MENTHLTH'].unique())


[88. 15.  1. 77. 30.  2.  8. 10.  7.  6.  5.  4.  9. 99. 25. 20.  3. 29.
 11. 12. 14. 26. 17. 23. 21. 28. 18. 22. 13. 19. 16. 27. 24. nan]
MENTHLTH
7.0     286342
30.0     27295
2.0      25180
5.0      21369
10.0     16465
3.0      15961
1.0      15412
15.0     15317
20.0      9721
4.0       8381
25.0      3346
14.0      2847
6.0       2374
8.0       1873
12.0      1334
28.0       932
21.0       549
29.0       491
18.0       347
9.0        332
16.0       297
17.0       291
27.0       236
13.0       187
22.0       186
11.0       145
24.0       134
23.0       132
26.0       123
19.0        71
Name: count, dtype: int64
[ 7. 15.  1. 30.  2.  8. 10.  6.  5.  4.  9. 25. 20.  3. 29. 11. 12. 14.
 26. 17. 23. 21. 28. 18. 22. 13. 19. 16. 27. 24.]


In [61]:
# 1️ Check unique values (including NaN)
print(df['POORHLTH'].unique())

# 2️ Replace invalid codes with NaN
df['POORHLTH'] = df['POORHLTH'].replace([77, 88, 99], np.nan)

# 3️ Fill NaN with median (numeric "days" variable)
df['POORHLTH'] = df['POORHLTH'].fillna(df['POORHLTH'].median())

#  Check updated values
print(df['POORHLTH'].value_counts(dropna=False))
print(df['POORHLTH'].unique())


[88. nan  1. 14. 30. 20. 10. 25.  8.  2. 15.  4.  5.  3. 77. 28. 18.  7.
 12.  6. 21.  9. 27. 99. 16. 24. 13. 19. 26. 23. 17. 11. 29. 22.]
POORHLTH
7.0     337829
30.0     21013
2.0      16082
5.0      13184
1.0      12487
3.0      10938
15.0     10360
10.0     10316
20.0      6572
4.0       6132
14.0      2696
25.0      2354
6.0       1919
8.0       1583
12.0       972
21.0       639
28.0       520
9.0        298
18.0       264
16.0       255
17.0       184
29.0       182
27.0       155
13.0       140
22.0       132
24.0       119
23.0       105
11.0       101
26.0        92
19.0        47
Name: count, dtype: int64
[ 7.  1. 14. 30. 20. 10. 25.  8.  2. 15.  4.  5.  3. 28. 18. 12.  6. 21.
  9. 27. 16. 24. 13. 19. 26. 23. 17. 11. 29. 22.]


In [62]:
# 1️ Check unique values (including NaN)
print(df['PERSDOC3'].unique())

# 2️ Replace invalid codes with NaN
df['PERSDOC3'] = df['PERSDOC3'].replace([7, 9], np.nan)

# 3️ Fill NaN with mode (categorical variable)
df['PERSDOC3'] = df['PERSDOC3'].fillna(df['PERSDOC3'].mode()[0])

#  Check updated values
print(df['PERSDOC3'].value_counts(dropna=False))
print(df['PERSDOC3'].unique())


[ 2.  1.  3.  9.  7. nan]
PERSDOC3
1.0    247006
2.0    154558
3.0     56106
Name: count, dtype: int64
[2. 1. 3.]


In [63]:
# 1️ Check unique values (including NaN)
print(df['MEDCOST1'].unique())

# 2️ Replace invalid codes with NaN
df['MEDCOST1'] = df['MEDCOST1'].replace([7, 9], np.nan)

#  Fill NaN with mode (binary categorical)
df['MEDCOST1'] = df['MEDCOST1'].fillna(df['MEDCOST1'].mode()[0])

#  Check updated values
print(df['MEDCOST1'].value_counts(dropna=False))
print(df['MEDCOST1'].unique())


[ 2.  1.  7.  9. nan]
MEDCOST1
2.0    414307
1.0     43363
Name: count, dtype: int64
[2. 1.]


In [64]:
# 1️ Check unique values (including NaN)
print(df['EXERANY2'].unique())

# 2️ Replace invalid codes with NaN
df['EXERANY2'] = df['EXERANY2'].replace([7, 9], np.nan)

# 3️ Fill NaN with mode (binary categorical)
df['EXERANY2'] = df['EXERANY2'].fillna(df['EXERANY2'].mode()[0])

#  Check updated values
print(df['EXERANY2'].value_counts(dropna=False))
print(df['EXERANY2'].unique())


[ 1.  2.  9.  7. nan]
EXERANY2
1.0    351376
2.0    106294
Name: count, dtype: int64
[1. 2.]


In [65]:
# 1️ Check unique values (including NaN)
print(df['CVDSTRK3'].unique())

# 2️ Replace invalid codes with NaN
df['CVDSTRK3'] = df['CVDSTRK3'].replace([7, 9], np.nan)

# 3️ Fill NaN with mode (binary categorical)
df['CVDSTRK3'] = df['CVDSTRK3'].fillna(df['CVDSTRK3'].mode()[0])

#  Check updated values
print(df['CVDSTRK3'].value_counts(dropna=False))
print(df['CVDSTRK3'].unique())


[ 2.  1.  7.  9. nan]
CVDSTRK3
2.0    437009
1.0     20661
Name: count, dtype: int64
[2. 1.]


In [66]:
# 1️ Check unique values (including NaN)
print(df['ADDEPEV3'].unique())

# 2️ Replace invalid codes with NaN
df['ADDEPEV3'] = df['ADDEPEV3'].replace([7, 9], np.nan)

# 3️ Fill NaN with mode (binary categorical)
df['ADDEPEV3'] = df['ADDEPEV3'].fillna(df['ADDEPEV3'].mode()[0])

#  Check updated values
print(df['ADDEPEV3'].value_counts(dropna=False))
print(df['ADDEPEV3'].unique())


[ 2.  1.  7.  9. nan]
ADDEPEV3
2.0    361545
1.0     96125
Name: count, dtype: int64
[2. 1.]


In [67]:
# 1️ Check unique values (including NaN)
print(df['CHCKDNY2'].unique())

# 2️ Replace invalid codes with NaN
df['CHCKDNY2'] = df['CHCKDNY2'].replace([7, 9], np.nan)

# 3️ Fill NaN with mode (binary categorical)
df['CHCKDNY2'] = df['CHCKDNY2'].fillna(df['CHCKDNY2'].mode()[0])

#  Check updated values
print(df['CHCKDNY2'].value_counts(dropna=False))
print(df['CHCKDNY2'].unique())


[ 2.  1.  7.  9. nan]
CHCKDNY2
2.0    433918
1.0     23752
Name: count, dtype: int64
[2. 1.]


In [68]:
# 1️ Check unique values (including NaN)
print(df['MARITAL'].unique())

# 2️ Replace invalid codes with NaN
df['MARITAL'] = df['MARITAL'].replace([9], np.nan)

# 3️ Fill NaN with mode (categorical variable)
df['MARITAL'] = df['MARITAL'].fillna(df['MARITAL'].mode()[0])

#  Check updated values
print(df['MARITAL'].value_counts(dropna=False))
print(df['MARITAL'].unique())

[ 3.  1.  6.  5.  2.  9.  4. nan]
MARITAL
1.0    233615
5.0     84851
2.0     58827
3.0     49161
6.0     21754
4.0      9462
Name: count, dtype: int64
[3. 1. 6. 5. 2. 4.]


In [69]:
# 1️ Check unique values (including NaN)
print(df['EDUCA'].unique())

# 2️ Replace invalid codes with NaN
df['EDUCA'] = df['EDUCA'].replace([9], np.nan)

# 3️ Fill NaN with mode (categorical variable)
df['EDUCA'] = df['EDUCA'].fillna(df['EDUCA'].mode()[0])

#  Check updated values
print(df['EDUCA'].value_counts(dropna=False))
print(df['EDUCA'].unique())


[ 4.  6.  5.  3.  2.  9.  1. nan]
EDUCA
6.0    193912
5.0    120732
4.0    115877
3.0     17200
2.0      9226
1.0       723
Name: count, dtype: int64
[4. 6. 5. 3. 2. 1.]


In [70]:
# 1️ Check unique values (including NaN)
print(df['EMPLOY1'].unique())

# 2️ Replace invalid codes with NaN
df['EMPLOY1'] = df['EMPLOY1'].replace([9], np.nan)

# 3️ Fill NaN with mode (categorical variable)
df['EMPLOY1'] = df['EMPLOY1'].fillna(df['EMPLOY1'].mode()[0])

#  Check updated values
print(df['EMPLOY1'].value_counts(dropna=False))
print(df['EMPLOY1'].unique())


[ 7.  1.  8.  5. nan  2.  6.  3.  9.  4.]
EMPLOY1
1.0    194780
7.0    146916
2.0     39146
8.0     27758
5.0     17832
6.0     11473
4.0     10812
3.0      8953
Name: count, dtype: int64
[7. 1. 8. 5. 2. 6. 3. 4.]


In [71]:
# 1️ Check unique values (including NaN)
print(df['_INCOMG1'].unique())

# 2️ Replace invalid codes with NaN
df['_INCOMG1'] = df['_INCOMG1'].replace([9], np.nan)

# 3️ Fill NaN with mode (categorical variable)
df['_INCOMG1'] = df['_INCOMG1'].fillna(df['_INCOMG1'].mode()[0])

#  Check updated values
print(df['_INCOMG1'].value_counts(dropna=False))
print(df['_INCOMG1'].unique())


[9. 7. 4. 2. 6. 3. 5. 1.]
_INCOMG1
5.0    199832
6.0     82453
4.0     49686
3.0     41702
2.0     33503
7.0     29694
1.0     20800
Name: count, dtype: int64
[5. 7. 4. 2. 6. 3. 1.]


In [72]:
# 1️ Check unique values (including NaN)
print(df['DIFFWALK'].unique())

# 2️ Replace invalid codes with NaN
df['DIFFWALK'] = df['DIFFWALK'].replace([7, 9], np.nan)

# 3️ Fill NaN with mode (categorical variable)
df['DIFFWALK'] = df['DIFFWALK'].fillna(df['DIFFWALK'].mode()[0])

#  Check updated values
print(df['DIFFWALK'].value_counts(dropna=False))
print(df['DIFFWALK'].unique())


[ 2.  1. nan  7.  9.]
DIFFWALK
2.0    386245
1.0     71425
Name: count, dtype: int64
[2. 1.]


In [73]:
# 1️ Check unique values (including NaN)
print(df['SMOKE100'].unique())

# 2️ Replace invalid codes with NaN
df['SMOKE100'] = df['SMOKE100'].replace([7, 9], np.nan)

# 3️ Fill NaN with mode (categorical variable)
df['SMOKE100'] = df['SMOKE100'].fillna(df['SMOKE100'].mode()[0])

#  Check updated values
print(df['SMOKE100'].value_counts(dropna=False))
print(df['SMOKE100'].unique())


[ 2.  1. nan  7.  9.]
SMOKE100
2.0    290428
1.0    167242
Name: count, dtype: int64
[2. 1.]


In [74]:
# 1️ Check unique values (including NaN)
print(df['LSATISFY'].unique())

# 2️ Replace invalid codes with NaN
df['LSATISFY'] = df['LSATISFY'].replace([9,7], np.nan)

# 3️ Fill NaN with mode (categorical variable)
df['LSATISFY'] = df['LSATISFY'].fillna(df['LSATISFY'].mode()[0])

#  Check updated values
print(df['LSATISFY'].value_counts(dropna=False))
print(df['LSATISFY'].unique())


[ 1.  2.  3. nan  9.  4.  7.]
LSATISFY
2.0    355863
1.0     90530
3.0      8832
4.0      2445
Name: count, dtype: int64
[1. 2. 3. 4.]


In [75]:
df.columns

Index(['GENHLTH', '_SEX', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PERSDOC3',
       'MEDCOST1', 'EXERANY2', 'CVDSTRK3', 'CHCKDNY2', 'MARITAL', 'EDUCA',
       'EMPLOY1', '_INCOMG1', 'DIFFWALK', 'SMOKE100', 'LSATISFY', '_METSTAT',
       'SSBFRUT3', '_TOTINDA', '_IMPRACE', '_RFDRHV9', '_HLTHPL2', '_RACE',
       '_AGEG5YR', '_BMI5', 'ADDEPEV3', 'EMTSUPRT', '_RFDRHV9', 'DIABETE4'],
      dtype='object')

In [76]:
# 1️ Check unique values (including NaN)
print(df['_METSTAT'].unique())

# 2️ Replace invalid codes with NaN
df['_METSTAT'] = df['_METSTAT'].replace([9], np.nan)

# 3️ Fill NaN with mode (categorical variable)
df['_METSTAT'] = df['_METSTAT'].fillna(df['_METSTAT'].mode()[0])

#  Check updated values
print(df['_METSTAT'].value_counts(dropna=False))
print(df['_METSTAT'].unique())


[ 1.  2. nan]
_METSTAT
1.0    331702
2.0    125968
Name: count, dtype: int64
[1. 2.]


In [77]:
# 1️ Check unique values (including NaN)
print(df['SSBFRUT3'].unique())

# 2️ Replace invalid codes with NaN
df['SSBFRUT3'] = df['SSBFRUT3'].replace([777, 888, 999], np.nan)

# 3️ Fill NaN with median (numeric variable)
df['SSBFRUT3'] = df['SSBFRUT3'].fillna(df['SSBFRUT3'].median())

#  Check updated values
print(df['SSBFRUT3'].value_counts(dropna=False))
print(df['SSBFRUT3'].unique())
# 101 = 1 time per day
# 201 = 1 time per week
# 301 = 1 time per month
# 202 = 2 times per week
# 399 = 9 times per month
# etc.


[ nan 888. 101. 301. 201. 302. 102. 103. 999. 310. 304. 120. 303. 202.
 777. 203. 315. 205. 305. 330. 112. 106. 105. 204. 107. 104. 320. 312.
 131. 114. 309. 130. 307. 350. 314. 306. 325. 318. 110. 215. 206. 316.
 323. 308. 207. 210. 321. 199. 115. 399. 109. 208. 317. 214. 108. 150.
 327. 324. 335. 360. 328. 340. 322. 211. 329. 225. 230. 128. 125. 221.
 153. 242. 212. 124. 313. 338. 220. 122. 113. 326. 299. 311. 331. 291.
 222. 209. 364. 118. 260. 224. 140. 217. 388. 116. 228. 390. 213.]
SSBFRUT3
202.0    413207
201.0      8844
101.0      7087
301.0      5340
302.0      4862
          ...  
140.0         1
388.0         1
116.0         1
228.0         1
213.0         1
Name: count, Length: 93, dtype: int64
[202. 101. 301. 201. 302. 102. 103. 310. 304. 120. 303. 203. 315. 205.
 305. 330. 112. 106. 105. 204. 107. 104. 320. 312. 131. 114. 309. 130.
 307. 350. 314. 306. 325. 318. 110. 215. 206. 316. 323. 308. 207. 210.
 321. 199. 115. 399. 109. 208. 317. 214. 108. 150. 327. 324. 335. 360.


In [78]:
# 1️ Check unique values (including NaN)
print(df['_TOTINDA'].unique())

# 2️ Replace invalid codes with NaN
df['_TOTINDA'] = df['_TOTINDA'].replace([9], np.nan)

# 3️ Fill NaN with mode (categorical variable)
df['_TOTINDA'] = df['_TOTINDA'].fillna(df['_TOTINDA'].mode()[0])

#  Check updated values
print(df['_TOTINDA'].value_counts(dropna=False))
print(df['_TOTINDA'].unique())


[1. 2. 9.]
_TOTINDA
1.0    351376
2.0    106294
Name: count, dtype: int64
[1. 2.]


In [79]:
# 1️ Check unique values (including NaN)
print(df['_IMPRACE'].unique())

# 2️ (No invalid codes, so nothing to replace)

# 3️ If NaN exists, fill using mode
df['_IMPRACE'] = df['_IMPRACE'].fillna(df['_IMPRACE'].mode()[0])

#  Check updated values
print(df['_IMPRACE'].value_counts(dropna=False))
print(df['_IMPRACE'].unique())


[1. 6. 2. 3. 5. 4.]
_IMPRACE
1.0    336908
5.0     48961
2.0     35559
6.0     16861
3.0     12760
4.0      6621
Name: count, dtype: int64
[1. 6. 2. 3. 5. 4.]


In [80]:
df.columns

Index(['GENHLTH', '_SEX', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PERSDOC3',
       'MEDCOST1', 'EXERANY2', 'CVDSTRK3', 'CHCKDNY2', 'MARITAL', 'EDUCA',
       'EMPLOY1', '_INCOMG1', 'DIFFWALK', 'SMOKE100', 'LSATISFY', '_METSTAT',
       'SSBFRUT3', '_TOTINDA', '_IMPRACE', '_RFDRHV9', '_HLTHPL2', '_RACE',
       '_AGEG5YR', '_BMI5', 'ADDEPEV3', 'EMTSUPRT', '_RFDRHV9', 'DIABETE4'],
      dtype='object')

In [81]:
df.columns[df.columns.duplicated()]

Index(['_RFDRHV9'], dtype='object')

In [82]:
# Removing duplicated column names (e.g., '_RFDRHV9' appeared twice).
df = df.loc[:, ~df.columns.duplicated()]

In [83]:
df.columns

Index(['GENHLTH', '_SEX', 'PHYSHLTH', 'MENTHLTH', 'POORHLTH', 'PERSDOC3',
       'MEDCOST1', 'EXERANY2', 'CVDSTRK3', 'CHCKDNY2', 'MARITAL', 'EDUCA',
       'EMPLOY1', '_INCOMG1', 'DIFFWALK', 'SMOKE100', 'LSATISFY', '_METSTAT',
       'SSBFRUT3', '_TOTINDA', '_IMPRACE', '_RFDRHV9', '_HLTHPL2', '_RACE',
       '_AGEG5YR', '_BMI5', 'ADDEPEV3', 'EMTSUPRT', 'DIABETE4'],
      dtype='object')

In [84]:
df.shape

(457670, 29)

In [85]:
# 1️ Check unique values (including NaN)
print(df['_RFDRHV9'].unique())

# 2️ Replace invalid codes with NaN using .loc
df.loc[:, '_RFDRHV9'] = df['_RFDRHV9'].replace([9], np.nan)

# 3️ Fill NaN with mode using .loc
df.loc[:, '_RFDRHV9'] = df['_RFDRHV9'].fillna(df['_RFDRHV9'].mode()[0])

#  Check updated values
print(df['_RFDRHV9'].value_counts(dropna=False))
print(df['_RFDRHV9'].unique())

# here replacement is not trustable becuase there must be small heavy drinkers so will remove it later.

[1. 9. 2.]
_RFDRHV9
1.0    433510
2.0     24160
Name: count, dtype: int64
[1. 2.]


In [86]:
# 1️ Check unique values (including NaN)
print(df['_HLTHPL2'].unique())

# 2️ Replace invalid codes with NaN
df.loc[:, '_HLTHPL2'] = df['_HLTHPL2'].replace([9], np.nan)

# 3️ Fill NaN with mode (categorical variable)
df.loc[:, '_HLTHPL2'] = df['_HLTHPL2'].fillna(df['_HLTHPL2'].mode()[0])

#  Check updated values
print(df['_HLTHPL2'].value_counts(dropna=False))
print(df['_HLTHPL2'].unique())


[1. 9. 2.]
_HLTHPL2
1.0    432264
2.0     25406
Name: count, dtype: int64
[1. 2.]


In [87]:
# 1️ Check unique values (including NaN)
print(df['_RACE'].unique())

# 2️ Replace invalid codes with NaN
df.loc[:, '_RACE'] = df['_RACE'].replace([9], np.nan)

# 3️ Fill NaN with mode (categorical variable)
df.loc[:, '_RACE'] = df['_RACE'].fillna(df['_RACE'].mode()[0])

#  Check updated values
print(df['_RACE'].value_counts(dropna=False))
print(df['_RACE'].unique())


[1. 7. 2. 4. 8. 9. 6. 3. 5.]
_RACE
1.0    338449
8.0     48646
2.0     35172
4.0     12646
7.0     10486
3.0      6460
6.0      3737
5.0      2074
Name: count, dtype: int64
[1. 7. 2. 4. 8. 6. 3. 5.]


In [88]:
# 1️ Check unique values (including NaN)
print(df['_AGEG5YR'].unique())

# Remove rows where _AGEG5YR is NaN or 14
df = df[~df['_AGEG5YR'].isin([np.nan, 14])]

#  Check updated values
print(df['_AGEG5YR'].value_counts(dropna=False))
print(df['_AGEG5YR'].unique())


[12. 13.  8.  6.  7. 11. 10.  9.  1.  5. 14.  4.  2.  3.]
_AGEG5YR
10.0    47701
11.0    44774
9.0     43387
13.0    41756
12.0    36803
8.0     34936
7.0     31698
5.0     30899
1.0     29692
6.0     28968
4.0     28804
3.0     26237
2.0     23705
Name: count, dtype: int64
[12. 13.  8.  6.  7. 11. 10.  9.  1.  5.  4.  2.  3.]


In [89]:
# 1️ Check unique values (including NaN)
print(df['_BMI5'].unique())

# 2️ Replace invalid codes with NaN
df.loc[:, '_BMI5'] = df['_BMI5'].replace([9999], np.nan)

# 3️ Fill NaN with median (numeric variable)
df.loc[:, '_BMI5'] = df['_BMI5'].fillna(df['_BMI5'].median())

#  Check updated values
print(df['_BMI5'].describe())
print(df['_BMI5'].unique()[:30])  # show first 20 unique values


[2249. 2583. 2253. ... 4246. 4595. 4065.]
count    449360.000000
mean       2847.259812
std         630.483530
min        1200.000000
25%        2441.000000
50%        2744.000000
75%        3125.000000
max        9984.000000
Name: _BMI5, dtype: float64
[2249. 2583. 2253. 2509. 1977. 3336. 3147. 3649. 4121. 2129. 2510. 2441.
 2740. 2502. 2506. 2962. 2343. 3018. 2912. 2500. 2689. 2769. 2455. 2979.
 2744. 4100. 3067. 2551. 2158. 3132.]


In [90]:
print(df['_BMI5'].describe())

count    449360.000000
mean       2847.259812
std         630.483530
min        1200.000000
25%        2441.000000
50%        2744.000000
75%        3125.000000
max        9984.000000
Name: _BMI5, dtype: float64


In [91]:
# 1️ Check unique values (including NaN)
print(df['ADDEPEV3'].unique())

# 2️ Replace invalid codes with NaN
df.loc[:, 'ADDEPEV3'] = df['ADDEPEV3'].replace([7, 9], np.nan)

# 3️ Fill NaN with mode (categorical variable)
df.loc[:, 'ADDEPEV3'] = df['ADDEPEV3'].fillna(df['ADDEPEV3'].mode()[0])

#  Check updated values
print(df['ADDEPEV3'].value_counts(dropna=False))
print(df['ADDEPEV3'].unique())


[2. 1.]
ADDEPEV3
2.0    354189
1.0     95171
Name: count, dtype: int64
[2. 1.]


In [92]:
df.shape

(449360, 29)

In [93]:
# 1️ Check unique values (including NaN)
print(df['EMTSUPRT'].unique())
print(df['EMTSUPRT'].value_counts(dropna=False))

# 2️ Replace invalid codes with NaN
df.loc[:, 'EMTSUPRT'] = df['EMTSUPRT'].replace([7, 9], np.nan)

# 3️ Fill NaN with mode (categorical/ordinal variable)
df.loc[:, 'EMTSUPRT'] = df['EMTSUPRT'].fillna(df['EMTSUPRT'].mode()[0])

#  Check updated values
print(df['EMTSUPRT'].value_counts(dropna=False))
print(df['EMTSUPRT'].unique())


[ 1.  2.  4.  5.  3.  7. nan  9.]
EMTSUPRT
NaN    248953
1.0     95047
2.0     59155
3.0     26731
4.0      8562
5.0      8229
7.0      1951
9.0       732
Name: count, dtype: int64
EMTSUPRT
1.0    346683
2.0     59155
3.0     26731
4.0      8562
5.0      8229
Name: count, dtype: int64
[1. 2. 4. 5. 3.]


In [94]:
df.shape

(449360, 29)

In [95]:
# 1️ Check unique values (including NaN)
print(df['DIABETE4'].unique())

# 2️ Replace invalid codes with NaN
df.loc[:, 'DIABETE4'] = df['DIABETE4'].replace([7, 9], np.nan)

# 3️ Fill NaN with mode (categorical variable)
df.loc[:, 'DIABETE4'] = df['DIABETE4'].fillna(df['DIABETE4'].mode()[0])

#  Check updated values
print(df['DIABETE4'].value_counts(dropna=False))
print(df['DIABETE4'].unique())


[3. 1. 4. 2. 7. 9.]
DIABETE4
3.0    370009
1.0     64821
4.0     11187
2.0      3343
Name: count, dtype: int64
[3. 1. 4. 2.]


In [96]:
df.isna().sum()

GENHLTH     0
_SEX        0
PHYSHLTH    0
MENTHLTH    0
POORHLTH    0
PERSDOC3    0
MEDCOST1    0
EXERANY2    0
CVDSTRK3    0
CHCKDNY2    0
MARITAL     0
EDUCA       0
EMPLOY1     0
_INCOMG1    0
DIFFWALK    0
SMOKE100    0
LSATISFY    0
_METSTAT    0
SSBFRUT3    0
_TOTINDA    0
_IMPRACE    0
_RFDRHV9    0
_HLTHPL2    0
_RACE       0
_AGEG5YR    0
_BMI5       0
ADDEPEV3    0
EMTSUPRT    0
DIABETE4    0
dtype: int64

    # At this stage, all missing values have been handled.
    # Invalid codes were converted to NaN and imputed using appropriate methods.
    # The dataset now contains no missing values and is ready for further preprocessing.


In [97]:
df.shape

(449360, 29)

In [98]:
df.head()

GENHLTH  _SEX  PHYSHLTH  MENTHLTH  POORHLTH  PERSDOC3  MEDCOST1  EXERANY2  \
0      3.0   2.0       2.0       7.0       7.0       2.0       2.0       1.0   
1      1.0   1.0       6.0       7.0       7.0       1.0       2.0       1.0   
2      2.0   1.0      30.0       7.0       1.0       3.0       1.0       1.0   
3      1.0   1.0       6.0       7.0       7.0       1.0       2.0       1.0   
4      3.0   1.0       6.0       7.0       7.0       1.0       2.0       2.0   

   CVDSTRK3  CHCKDNY2  MARITAL  EDUCA  EMPLOY1  _INCOMG1  DIFFWALK  SMOKE100  \
0       2.0       2.0      3.0    4.0      7.0       5.0       2.0       2.0   
1       2.0       2.0      1.0    6.0      7.0       7.0       2.0       1.0   
2       2.0       2.0      6.0    5.0      1.0       5.0       2.0       1.0   
3       2.0       2.0      1.0    6.0      7.0       4.0       2.0       2.0   
4       2.0       2.0      5.0    5.0      8.0       2.0       1.0       2.0   

   LSATISFY  _METSTAT  SSBFRUT3  _TOTINDA  _IMPRACE  _RFDRHV9  _HLTHPL2  \
0       1.0       1.0     202.0       1.0       1.0       1.0       1.0   
1       1.0       1.0     202.0       1.0       1.0       1.0       1.0   
2       1.0       2.0     202.0       1.0       1.0       1.0       1.0   
3       1.0       2.0     202.0       1.0       1.0       1.0       1.0   
4       2.0       1.0     202.0       2.0       1.0       1.0       1.0   

   _RACE  _AGEG5YR   _BMI5  ADDEPEV3  EMTSUPRT  DIABETE4  
0    1.0      12.0  2249.0       2.0       1.0       3.0  
1    1.0      13.0  2583.0       2.0       1.0       3.0  
2    1.0       8.0  2253.0       2.0       2.0       3.0  
3    1.0      13.0  2509.0       2.0       1.0       3.0  
4    1.0       6.0  1977.0       2.0       4.0       3.0

###  Saving the Cleaned Dataset  
The final cleaned and imputed dataset is exported as a CSV file.  
This allows reloading the processed data directly in future sessions without repeating the entire cleaning pipeline.


In [ ]:
# Save the cleaned dataset
df.to_csv("CLEANED_IMPUTED_BRFSS24.csv", index=False)

In [99]:
print("✅ Dataset saved as CLEANED_IMPUTED_BRFSS24.csv")

✅ Dataset saved as CLEANED_IMPUTED_BRFSS24.csv


###  Next Step: Preparing Data for Modeling , In the upcoming step, this cleaned dataset will be used for:
- Replacing and mapping categorical codes into meaningful numeric values  
- Converting the crucial target variable (`DIABETE4`) into a binary format (0 = No diabetes, 1 = Diabetes)  
- Preparing all features in a modeling-friendly structure  

This ensures the dataset is structured correctly before moving into EDA and machine learning.
